language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - nightly

matrix:
  allow_failures:
  - php: nightly

env:
  - COMPOSER_OPTS=""
  - COMPOSER_OPTS="--prefer-lowest"

install:
  - composer update $COMPOSER_OPTS

script:
  - vendor/bin/phpunit
  - vendor/bin/composer-require-checker

jobs:
  include:

    - stage: code quality
      script:
        - vendor/bin/phpstan analyse --level=max src tests

git:
  depth: 5

group: travis_latest
