language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - nightly

matrix:
  allow_failures:
  - php: nightly

env:
  - COMPOSER_OPTS=""
  - COMPOSER_OPTS="--prefer-lowest"

install:
  - composer update $COMPOSER_OPTS

script:
  - vendor/bin/phpunit
  - vendor/bin/composer-require-checker

git:
  depth: 5
